name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Untasky App
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.UNTASKY_SSH_HOST}}
          key: ${{secrets.UNTASKY_SSH_KEY}}
          username: ${{secrets.UNTASKY_SSH_USER}}

          script: |
            cd /var/www/html/untasky
            git pull origin master
            npm run build
            pm2 start npm -- start
            echo 'Deployment successful'
